### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by truffo** [mynameislau/clic-clac#1]
Un collègue :) a intégré ce composant dans une application, est ce que tu peux publier un tag si la version est stable ?

**Comment by mynameislau** [comment]
Tag créé mais par contre ce petit bout de code a évolué depuis il faudra juste que je commit la nouvelle version. Et d'ailleurs j'aurais bien aimé avoir ton avis niveau accessibilité. Tu me diras si c'est OK pour toi niveau tag
